export const de = {
  app: {
    name: "Studinance",
    tagline: "Finanzen für Studierende",
  },
  nav: {
    dashboard: "Übersicht",
    budget: "Budget",
    goals: "Sparziele",
    bafoeg: "BAföG",
    jobs: "Jobs",
    marketplace: "Marktplatz",
    profile: "Profil",
  },
  auth: {
    welcome: "Willkommen zurück",
    signupTitle: "Konto erstellen",
    email: "E-Mail",
    password: "Passwort",
    signin: "Anmelden",
    signup: "Registrieren",
    google: "Mit Google fortfahren",
    or: "oder",
    haveAccount: "Schon ein Konto?",
    noAccount: "Noch kein Konto?",
    signinHere: "Hier anmelden",
    signupHere: "Hier registrieren",
    signout: "Abmelden",
    error: "Anmeldung fehlgeschlagen",
    success: "Erfolgreich registriert! Du kannst dich jetzt anmelden.",
  },
  onboarding: {
    step: "Schritt",
    of: "von",
    next: "Weiter",
    back: "Zurück",
    finish: "Loslegen",
    welcome: "Willkommen bei Studinance!",
    welcomeText: "In nur 3 Schritten richten wir deine App ein.",
    nameLabel: "Wie heißt du?",
    namePlaceholder: "Vorname",
    hochschuleLabel: "Wo studierst du?",
    hochschulePlaceholder: "z. B. TU München",
    semesterLabel: "Welches Semester?",
    budgetTitle: "Dein monatliches Budget",
    budgetText: "Wie viel Geld hast du pro Monat zur Verfügung?",
    budgetLabel: "Monatliches Budget (€)",
    bafoegTitle: "BAföG-Status",
    bafoegText: "Bekommst du BAföG?",
    bafoegYes: "Ja, ich beziehe BAföG",
    bafoegApplied: "Habe Antrag gestellt",
    bafoegNo: "Nein",
  },
  dashboard: {
    greeting: "Hallo",
    greetingNoName: "Willkommen",
    monthlyBudget: "Monatsbudget",
    spent: "Ausgegeben",
    remaining: "Verfügbar",
    income: "Einnahmen",
    expenses: "Ausgaben",
    insights: "Smarte Insights",
    upcomingDeadlines: "Anstehende Fristen",
    noDeadlines: "Keine anstehenden Fristen",
    quickAdd: "Schnell hinzufügen",
    savingsGoal: "Sparziel",
    streak: "Streak",
    days: "Tage",
    spendingTrend: "Ausgaben-Trend",
    last6Months: "Letzte 6 Monate",
    last2Months: "Letzte 2 Monate",
    noTrendData: "Noch zu wenig Daten für den Trend.",
  },
  budget: {
    title: "Budget Tracker",
    addTransaction: "Transaktion hinzufügen",
    editTransaction: "Transaktion bearbeiten",
    type: "Typ",
    income: "Einnahme",
    expense: "Ausgabe",
    amount: "Betrag",
    category: "Kategorie",
    date: "Datum",
    note: "Notiz (optional)",
    save: "Speichern",
    cancel: "Abbrechen",
    overview: "Monatsübersicht",
    distribution: "Verteilung",
    recent: "Letzte Transaktionen",
    noTransactions: "Noch keine Transaktionen. Füge deine erste hinzu!",
    deleted: "Transaktion gelöscht",
    saved: "Transaktion gespeichert",
    delete: "Löschen",
    exportCsv: "CSV exportieren",
    exportCsvDesc: "Alle Transaktionen dieses Monats als CSV herunterladen",
  },
  categories: {
    rent: "Miete",
    food: "Essen",
    transport: "Transport",
    leisure: "Freizeit",
    education: "Bildung",
    health: "Gesundheit",
    other: "Sonstiges",
    salary: "Gehalt",
    bafoeg: "BAföG",
    parents: "Eltern",
    side_job: "Nebenjob",
  },
  deleteConfirm: {
    title: "Wirklich löschen?",
    descTransaction: "Diese Transaktion wird dauerhaft gelöscht und kann nicht wiederhergestellt werden.",
    descDeadline: "Diese Frist wird dauerhaft gelöscht.",
    confirm: "Löschen",
    cancel: "Abbrechen",
  },
  bafoeg: {
    title: "BAföG Guide",
    subtitle: "Schritt für Schritt zum maximalen BAföG",
    applyTitle: "Antrag stellen",
    applySubtitle: "Stelle deinen Antrag direkt online – offiziell oder mit unserem Partner.",
    officialTitle: "BAföG Digital",
    officialDesc: "Offizieller Online-Antrag des Bundes – kostenlos.",
    officialBadge: "Offiziell",
    partnerTitle: "MeinBafög",
    partnerDesc: "Geführter Antrag in 30 Min. – Berechnung & Tipps inklusive.",
    partnerBadge: "Partner",
    steps: "Antragsschritte",
    checklist: "Dokumenten-Checkliste",
    deadlines: "Meine Fristen",
    addDeadline: "Frist hinzufügen",
    deadlineTitle: "Bezeichnung",
    deadlineDate: "Fälligkeitsdatum",
    tips: "Tipps zur Maximierung",
    step1: "Form 1: Hauptantrag ausfüllen",
    step1Desc: "Persönliche Angaben, Studium und Wohnsituation.",
    step2: "Einkommensnachweise sammeln",
    step2Desc: "Eltern-Steuerbescheid des vorletzten Jahres.",
    step3: "Antrag einreichen",
    step3Desc: "Online via BAföG Digital oder beim Studierendenwerk.",
    step4: "Auf Bescheid warten",
    step4Desc: "Bearbeitungszeit ca. 6–8 Wochen.",
    docs: {
      id: "Personalausweis-Kopie",
      enrollment: "Immatrikulationsbescheinigung",
      taxParents: "Einkommensteuerbescheid Eltern",
      bankStatement: "Kontoauszüge",
      rental: "Mietvertrag",
      health: "Krankenversicherungsnachweis",
    },
    tip1: "Stelle den Antrag rechtzeitig vor Semesterbeginn.",
    tip2: "Auch Vorabentscheid möglich, bevor du immatrikuliert bist.",
    tip3: "Werkstudentenjobs zählen bis 6.240 €/Jahr nicht zum Einkommen.",
    tip4: "Wer ausziehen will: BAföG-Höchstsatz nur bei eigener Wohnung.",
  },
  jobs: {
    title: "Werkstudentenjobs",
    filterCity: "Stadt",
    filterRemote: "Nur Remote",
    filterMinWage: "Min. Stundenlohn",
    all: "Alle",
    remote: "Remote",
    onsite: "Vor Ort",
    perHour: "/ Std.",
    apply: "Bewerben",
    applyNow: "Jetzt bewerben",
    markApplied: "Als beworben markieren",
    applied: "Beworben ✓",
    aiMatch: "KI-Matching (Premium)",
    aiMatchDesc: "Personalisierte Job-Empfehlungen basierend auf deinem Profil.",
    noJobs: "Keine Jobs gefunden.",
    search: "Jobs suchen …",
    sort: "Sortieren",
    sortNewest: "Neueste zuerst",
    sortHighestWage: "Höchster Lohn",
    count_one: "{{count}} Job gefunden",
    count_other: "{{count}} Jobs gefunden",
    saved: "Gemerkt",
    save: "Merken",
    unsave: "Entfernen",
    savedSection: "Gemerkte Jobs",
    noSaved: "Noch keine Jobs gemerkt.",
  },
  marketplace: {
    title: "Community Marktplatz",
    comingSoon: "Bald verfügbar",
    description: "Kleinanzeigen für Studierende: Möbel, WG-Zimmer, Bücher und mehr.",
    notify: "Benachrichtige mich",
    notifyPlaceholder: "deine@email.de",
    notifyDesc: "Sei der Erste, wenn der Marktplatz live geht. Kein Spam, versprochen.",
    notifySuccess: "Danke! Wir melden uns, wenn's so weit ist. 🎉",
    previewTitle: "So wird's aussehen",
    previewBadge: "Vorschau",
  },
  profile: {
    title: "Mein Profil",
    name: "Name",
    hochschule: "Hochschule",
    semester: "Semester",
    bafoegStatus: "BAföG-Status",
    monthlyBudget: "Monatliches Budget",
    savingsGoal: "Sparziel",
    language: "Sprache",
    save: "Änderungen speichern",
    saved: "Profil gespeichert",
    premium: "Premium",
    free: "​Free Plan\n",
    upgradeToPro: "Upgrade auf Premium",
    premiumActive: "Premium aktiv",
    premiumDesc: "Erweiterte Insights, KI-Job-Matching und mehr.",
    manageSub: "Abo verwalten",
    pricePerMonth: "3,99 € / Monat",
    cancelSub: "Abo kündigen",
    cancelConfirmTitle: "Premium wirklich kündigen?",
    cancelConfirmDesc: "Du behältst deine Premium-Funktionen bis zum Ende des aktuellen Abrechnungszeitraums. Danach verlierst du:",
    cancelDrawback1: "Erweiterte Insights & Ausgaben-Prognosen",
    cancelDrawback2: "6-Monats-Trend statt nur 2 Monate",
    cancelDrawback3: "KI-basiertes Job-Matching",
    cancelDrawback4: "CSV-Export deiner Transaktionen",
    cancelDrawback5: "Personalisierte BAföG-Tools",
    cancelKeep: "Doch behalten",
    cancelConfirm: "Ja, kündigen",
    cancelSuccess: "Abo gekündigt – aktiv bis {{date}}",
    cancelAlready: "Abo ist bereits gekündigt – aktiv bis {{date}}",
    cancelEndsOn: "Dein Abo läuft am {{date}} aus",
    upgradeBenefits: {
      analytics: "Erweiterte Analysen & Insights",
      ai: "KI-basiertes Job-Matching",
      forecast: "Ausgaben-Prognose",
      bafoeg: "Personalisierte BAföG-Tools",
      export: "CSV-Export",
    },
  },
  insights: {
    foodHigh: "Du gibst {{percent}}% für Essen aus – über dem Durchschnitt von 20%.",
    rentHigh: "Deine Miete macht {{percent}}% deines Budgets aus.",
    onTrack: "Super! Du bleibst {{amount}} € unter deinem Budget.",
    overBudget: "Achtung: Du hast dein Budget um {{amount}} € überschritten.",
    noData: "Erfasse Transaktionen, um Insights zu erhalten.",
    savingsProgress: "Du hast {{percent}}% deines Sparziels erreicht.",
  },
  premiumGate: {
    title: "Premium-Funktion",
    description: "Schalte erweiterte Insights, Prognosen und mehr frei – ab 3,99 €/Monat.",
    cta: "Jetzt upgraden",
    badge: "Premium",
  },
  premiumInsights: {
    title: "Erweiterte Insights",
    forecast: "Voraussichtliche Ausgaben Monatsende: € {{amount}}",
    topCategory: "Größte Kategorie: {{cat}} ({{percent}}%)",
    avgDaily: "Durchschnitt pro Tag: € {{amount}}",
    trend: "Trend vs. Vormonat: {{trend}}",
    noData: "Noch nicht genug Daten für erweiterte Analysen.",
  },
  checkoutSuccess: {
    title: "Premium freigeschaltet 🎉",
    subtitle: "Vielen Dank für dein Abo! Alle Premium-Funktionen sind ab sofort verfügbar.",
    feature1: "Erweiterte Insights & Prognosen",
    feature2: "6-Monats-Trend & CSV-Export",
    feature3: "Job-Match & alle Premium-Tools",
    ctaPremium: "Premium-Funktionen entdecken",
    ctaProfile: "Abo verwalten",
    syncing: "Abo wird synchronisiert…",
  },
  common: {
    loading: "Lädt...",
    error: "Fehler aufgetreten",
    retry: "Erneut versuchen",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    close: "Schließen",
    yes: "Ja",
    no: "Nein",
  },
  goals: {
    title: "Sparziele",
    subtitle: "Setze dir konkrete Ziele und verfolge deinen Fortschritt.",
    add: "Ziel hinzufügen",
    edit: "Ziel bearbeiten",
    titleLabel: "Bezeichnung",
    titlePlaceholder: "z. B. Laptop, Urlaub, Notgroschen",
    target: "Zielbetrag (€)",
    current: "Aktuell (€)",
    deadlineOptional: "Frist (optional)",
    until: "bis",
    saved: "Sparziel gespeichert",
    deleted: "Sparziel gelöscht",
    deleteDesc: "Dieses Sparziel wird dauerhaft gelöscht.",
    empty: "Noch keine Sparziele",
    emptyDesc: "Lege dein erstes Sparziel an, um deinen Fortschritt zu sehen.",
    freeUsage: "{{used}} / {{max}} Sparziele genutzt (Free Plan)",
    limitReached: "Limit erreicht – upgrade auf Premium für unbegrenzte Ziele.",
    unlimitedTitle: "Unbegrenzte Sparziele",
    unlimitedDesc: "Mit Premium kannst du beliebig viele Ziele verfolgen.",
  },
  catBudgets: {
    title: "Kategorie-Budgets",
    add: "Limit hinzufügen",
    limit: "Monatliches Limit (€)",
    saved: "Budget gespeichert",
    invalidLimit: "Bitte gültigen Betrag eingeben",
    empty: "Noch keine Kategorie-Limits gesetzt.",
    limitReached: "Free Plan Limit erreicht",
    limitReachedDesc: "Mit Premium kannst du beliebig viele Kategorie-Budgets festlegen.",
  },
  recurring: {
    title: "Wiederkehrende Transaktionen",
    add: "Hinzufügen",
    day: "Tag im Monat",
    saved: "Gespeichert",
    invalidAmount: "Bitte gültigen Betrag eingeben",
    empty: "Lege z. B. Miete oder Gehalt an, dann werden sie jeden Monat automatisch erfasst.",
    everyMonth: "Jeden Monat am {{day}}.",
  },
  aiCoach: {
    title: "KI-Finanzcoach",
    subtitle: "Persönliche Tipps zu deinen Ausgaben – generiert mit KI.",
    ask: "Tipps holen",
    hint: "Klicke auf \"Tipps holen\", um eine personalisierte Analyse deiner Finanzen zu erhalten.",
    rateLimit: "Zu viele Anfragen, bitte später erneut versuchen.",
    creditsOut: "AI-Guthaben aufgebraucht.",
    error: "KI-Coach konnte nicht antworten.",
  },
  landing: {
    hero: "Deine Finanzen. Dein Studium. Klar im Griff.",
    sub: "Studinance hilft dir, Ausgaben zu tracken, BAföG zu maximieren und den perfekten Werkstudentenjob zu finden.",
    cta: "Kostenlos starten",
    login: "Anmelden",
    feature1Title: "Smart Budgeting",
    feature1Desc: "Behalte den Überblick über Einnahmen und Ausgaben.",
    feature2Title: "BAföG optimieren",
    feature2Desc: "Schritt-für-Schritt zum maximalen Förderbetrag.",
    feature3Title: "Werkstudentenjobs",
    feature3Desc: "Finde flexible Jobs, die zu deinem Studium passen.",
    socialProof: "Bereits von 500+ Studierenden genutzt",
    howItWorksTitle: "So einfach geht's",
    howStep1Title: "Konto erstellen",
    howStep1Desc: "In unter 2 Minuten – kostenlos, ohne Kreditkarte.",
    howStep2Title: "Profil einrichten",
    howStep2Desc: "Budget, BAföG-Status und Hochschule hinterlegen.",
    howStep3Title: "Finanzen tracken",
    howStep3Desc: "Einnahmen & Ausgaben erfassen, Insights abrufen, fertig.",
    pricingTitle: "Transparent & fair",
    pricingSubtitle: "Starte kostenlos. Upgrade wenn du mehr willst.",
    freePlanName: "​Free Plan\n",
    freePlanPrice: "0 €",
    freePlanPeriod: "für immer",
    freePlanFeature1: "Budget-Tracker",
    freePlanFeature2: "BAföG Guide & Checkliste",
    freePlanFeature3: "Werkstudentenjobs",
    freePlanFeature4: "2 Monate Ausgaben-Verlauf",
    freeCta: "Jetzt starten",
    premiumPlanName: "Premium",
    premiumPlanPrice: "3,99 €",
    premiumPlanPeriod: "pro Monat",
    premiumPlanFeature1: "Alles aus dem Free Plan\n\n",
    premiumPlanFeature2: "KI Job-Matching",
    premiumPlanFeature3: "Erweiterte Insights & Prognosen",
    premiumPlanFeature4: "6 Monate Ausgaben-Trend",
    premiumPlanFeature5: "CSV-Export",
    premiumCta: "Premium testen",
  },
};
