export const en = {
  app: {
    name: "Studinance",
    tagline: "Finance for students",
  },
  nav: {
    dashboard: "Dashboard",
    budget: "Budget",
    goals: "Goals",
    bafoeg: "BAföG",
    jobs: "Jobs",
    marketplace: "Marketplace",
    profile: "Profile",
  },
  auth: {
    welcome: "Welcome back",
    signupTitle: "Create account",
    email: "Email",
    password: "Password",
    signin: "Sign in",
    signup: "Sign up",
    google: "Continue with Google",
    or: "or",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    signinHere: "Sign in here",
    signupHere: "Sign up here",
    signout: "Sign out",
    error: "Sign-in failed",
    success: "Account created! You can sign in now.",
  },
  onboarding: {
    step: "Step",
    of: "of",
    next: "Next",
    back: "Back",
    finish: "Get started",
    welcome: "Welcome to Studinance!",
    welcomeText: "Just 3 quick steps to set up your app.",
    nameLabel: "What's your name?",
    namePlaceholder: "First name",
    hochschuleLabel: "Where do you study?",
    hochschulePlaceholder: "e.g. TU Munich",
    semesterLabel: "Which semester?",
    budgetTitle: "Your monthly budget",
    budgetText: "How much money do you have available per month?",
    budgetLabel: "Monthly budget (€)",
    bafoegTitle: "BAföG status",
    bafoegText: "Do you receive BAföG (German student aid)?",
    bafoegYes: "Yes, I receive BAföG",
    bafoegApplied: "Application submitted",
    bafoegNo: "No",
  },
  dashboard: {
    greeting: "Hi",
    greetingNoName: "Welcome",
    monthlyBudget: "Monthly budget",
    spent: "Spent",
    remaining: "Available",
    income: "Income",
    expenses: "Expenses",
    insights: "Smart insights",
    upcomingDeadlines: "Upcoming deadlines",
    noDeadlines: "No upcoming deadlines",
    quickAdd: "Quick add",
    savingsGoal: "Savings goal",
    streak: "Streak",
    days: "days",
    spendingTrend: "Spending trend",
    last6Months: "Last 6 months",
    last2Months: "Last 2 months",
    noTrendData: "Not enough data for the trend yet.",
  },
  budget: {
    title: "Budget Tracker",
    addTransaction: "Add transaction",
    editTransaction: "Edit transaction",
    type: "Type",
    income: "Income",
    expense: "Expense",
    amount: "Amount",
    category: "Category",
    date: "Date",
    note: "Note (optional)",
    save: "Save",
    cancel: "Cancel",
    overview: "Monthly overview",
    distribution: "Distribution",
    recent: "Recent transactions",
    noTransactions: "No transactions yet. Add your first one!",
    deleted: "Transaction deleted",
    saved: "Transaction saved",
    delete: "Delete",
    exportCsv: "Export CSV",
    exportCsvDesc: "Download all transactions for this month as CSV",
  },
  categories: {
    rent: "Rent",
    food: "Food",
    transport: "Transport",
    leisure: "Leisure",
    education: "Education",
    health: "Health",
    other: "Other",
    salary: "Salary",
    bafoeg: "BAföG",
    parents: "Parents",
    side_job: "Side job",
  },
  deleteConfirm: {
    title: "Really delete?",
    descTransaction: "This transaction will be permanently deleted and cannot be recovered.",
    descDeadline: "This deadline will be permanently deleted.",
    confirm: "Delete",
    cancel: "Cancel",
  },
  bafoeg: {
    title: "BAföG Guide",
    subtitle: "Step by step to maximum funding",
    applyTitle: "Apply for BAföG",
    applySubtitle: "Submit your application online – official portal or via our partner.",
    officialTitle: "BAföG Digital",
    officialDesc: "Official federal online application – free of charge.",
    officialBadge: "Official",
    partnerTitle: "MeinBafög",
    partnerDesc: "Guided application in 30 min – with calculator and tips.",
    partnerBadge: "Partner",
    steps: "Application steps",
    checklist: "Document checklist",
    deadlines: "My deadlines",
    addDeadline: "Add deadline",
    deadlineTitle: "Title",
    deadlineDate: "Due date",
    tips: "Optimization tips",
    step1: "Form 1: Fill out main application",
    step1Desc: "Personal info, study details and housing situation.",
    step2: "Collect income proofs",
    step2Desc: "Parents' tax assessment from two years ago.",
    step3: "Submit application",
    step3Desc: "Online via BAföG Digital or at your student services office.",
    step4: "Wait for decision",
    step4Desc: "Processing usually takes 6–8 weeks.",
    docs: {
      id: "ID card copy",
      enrollment: "Enrollment certificate",
      taxParents: "Parents' tax assessment",
      bankStatement: "Bank statements",
      rental: "Rental contract",
      health: "Health insurance proof",
    },
    tip1: "Submit your application well before the semester starts.",
    tip2: "An advance decision is possible before enrollment.",
    tip3: "Working student jobs up to €6,240/year don't count as income.",
    tip4: "Maximum rate is only available if you live on your own.",
  },
  jobs: {
    title: "Working student jobs",
    filterCity: "City",
    filterRemote: "Remote only",
    filterMinWage: "Min. hourly wage",
    all: "All",
    remote: "Remote",
    onsite: "On-site",
    perHour: "/ hr",
    apply: "Apply",
    applyNow: "Apply now",
    markApplied: "Mark as applied",
    applied: "Applied ✓",
    aiMatch: "AI matching (Premium)",
    aiMatchDesc: "Personalized job recommendations based on your profile.",
    noJobs: "No jobs found.",
    search: "Search jobs…",
    sort: "Sort",
    sortNewest: "Newest first",
    sortHighestWage: "Highest wage",
    count_one: "{{count}} job found",
    count_other: "{{count}} jobs found",
    saved: "Saved",
    save: "Save",
    unsave: "Remove",
    savedSection: "Saved jobs",
    noSaved: "No jobs saved yet.",
  },
  marketplace: {
    title: "Community marketplace",
    comingSoon: "Coming soon",
    description: "Classifieds for students: furniture, shared rooms, books and more.",
    notify: "Notify me",
    notifyPlaceholder: "your@email.com",
    notifyDesc: "Be the first to know when the marketplace goes live. No spam, promise.",
    notifySuccess: "Thanks! We'll let you know when it's ready. 🎉",
    previewTitle: "Here's a preview",
    previewBadge: "Preview",
  },
  profile: {
    title: "My profile",
    name: "Name",
    hochschule: "University",
    semester: "Semester",
    bafoegStatus: "BAföG status",
    monthlyBudget: "Monthly budget",
    savingsGoal: "Savings goal",
    language: "Language",
    save: "Save changes",
    saved: "Profile saved",
    premium: "Premium",
    free: "​Free Plan\n",
    upgradeToPro: "Upgrade to Premium",
    premiumActive: "Premium active",
    premiumDesc: "Advanced insights, AI job matching and more.",
    manageSub: "Manage subscription",
    pricePerMonth: "€3.99 / month",
    cancelSub: "Cancel subscription",
    cancelConfirmTitle: "Cancel your premium?",
    cancelConfirmDesc: "You'll keep premium features until the end of your current billing period, then be downgraded automatically.",
    cancelKeep: "Keep premium",
    cancelConfirm: "Yes, cancel",
    cancelSuccess: "Subscription canceled – active until {{date}}",
    cancelAlready: "Subscription already canceled – active until {{date}}",
    cancelEndsOn: "Ends on {{date}}",
    upgradeBenefits: {
      analytics: "Advanced analytics & insights",
      ai: "AI-based job matching",
      forecast: "Spending forecast",
      bafoeg: "Personalized BAföG tools",
      export: "CSV export",
    },
  },
  insights: {
    foodHigh: "You spend {{percent}}% on food – above the 20% average.",
    rentHigh: "Rent makes up {{percent}}% of your budget.",
    onTrack: "Great! You're {{amount}} € below your budget.",
    overBudget: "Heads up: you exceeded your budget by {{amount}} €.",
    noData: "Add transactions to get insights.",
    savingsProgress: "You've reached {{percent}}% of your savings goal.",
  },
  premiumGate: {
    title: "Premium feature",
    description: "Unlock advanced insights, forecasts, and more – from €3.99/month.",
    cta: "Upgrade now",
    badge: "Premium",
  },
  premiumInsights: {
    title: "Advanced Insights",
    forecast: "Projected month-end spending: € {{amount}}",
    topCategory: "Top category: {{cat}} ({{percent}}%)",
    avgDaily: "Daily average: € {{amount}}",
    trend: "Trend vs. last month: {{trend}}",
    noData: "Not enough data yet for advanced analytics.",
  },
  checkoutSuccess: {
    title: "Premium unlocked 🎉",
    subtitle: "Thanks for subscribing! All premium features are now available.",
    feature1: "Advanced insights & forecasts",
    feature2: "6-month trend & CSV export",
    feature3: "Job match & all premium tools",
    ctaPremium: "Explore premium features",
    ctaProfile: "Manage subscription",
    syncing: "Syncing your subscription…",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try again",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    yes: "Yes",
    no: "No",
  },
  goals: {
    title: "Savings goals",
    subtitle: "Set concrete goals and track your progress.",
    add: "Add goal",
    edit: "Edit goal",
    titleLabel: "Name",
    titlePlaceholder: "e.g. Laptop, Vacation, Emergency fund",
    target: "Target amount (€)",
    current: "Current (€)",
    deadlineOptional: "Deadline (optional)",
    until: "until",
    saved: "Goal saved",
    deleted: "Goal deleted",
    deleteDesc: "This savings goal will be permanently deleted.",
    empty: "No savings goals yet",
    emptyDesc: "Create your first goal to track progress.",
    freeUsage: "{{used}} / {{max}} goals used (Free Plan)",
    limitReached: "Limit reached – upgrade to Premium for unlimited goals.",
    unlimitedTitle: "Unlimited savings goals",
    unlimitedDesc: "With Premium you can track as many goals as you want.",
  },
  catBudgets: {
    title: "Category budgets",
    add: "Add limit",
    limit: "Monthly limit (€)",
    saved: "Budget saved",
    invalidLimit: "Please enter a valid amount",
    empty: "No category limits set yet.",
    limitReached: "Free Plan limit reached",
    limitReachedDesc: "With Premium you can set unlimited category budgets.",
  },
  recurring: {
    title: "Recurring transactions",
    add: "Add",
    day: "Day of month",
    saved: "Saved",
    invalidAmount: "Please enter a valid amount",
    empty: "Add things like rent or salary – they'll be logged every month automatically.",
    everyMonth: "Every month on day {{day}}",
  },
  aiCoach: {
    title: "AI Finance Coach",
    subtitle: "Personalized tips for your spending – generated by AI.",
    ask: "Get tips",
    hint: "Click \"Get tips\" to receive a personalized analysis of your finances.",
    rateLimit: "Too many requests, please try again later.",
    creditsOut: "AI credits exhausted.",
    error: "AI coach could not respond.",
  },
  landing: {
    hero: "Your finances. Your studies. Under control.",
    sub: "Studinance helps you track expenses, maximize BAföG and find the perfect working student job.",
    cta: "Start for free",
    login: "Sign in",
    feature1Title: "Smart budgeting",
    feature1Desc: "Keep track of income and expenses.",
    feature2Title: "Optimize BAföG",
    feature2Desc: "Step by step to the maximum aid amount.",
    feature3Title: "Student jobs",
    feature3Desc: "Find flexible jobs that fit your studies.",
    socialProof: "Already used by 500+ students",
    howItWorksTitle: "Here's how it works",
    howStep1Title: "Create account",
    howStep1Desc: "In under 2 minutes – free, no credit card needed.",
    howStep2Title: "Set up profile",
    howStep2Desc: "Add your budget, BAföG status and university.",
    howStep3Title: "Track finances",
    howStep3Desc: "Log income & expenses, get insights, done.",
    pricingTitle: "Transparent & fair",
    pricingSubtitle: "Start free. Upgrade when you want more.",
    freePlanName: "​Free Plan\n",
    freePlanPrice: "€0",
    freePlanPeriod: "forever",
    freePlanFeature1: "Budget tracker",
    freePlanFeature2: "BAföG guide & checklist",
    freePlanFeature3: "Working student jobs",
    freePlanFeature4: "2 months spending history",
    freeCta: "Get started",
    premiumPlanName: "Premium",
    premiumPlanPrice: "€3.99",
    premiumPlanPeriod: "per month",
    premiumPlanFeature1: "Everything in the Free Plan\n\n",
    premiumPlanFeature2: "AI job matching",
    premiumPlanFeature3: "Advanced insights & forecasts",
    premiumPlanFeature4: "6-month spending trend",
    premiumPlanFeature5: "CSV export",
    premiumCta: "Try Premium",
  },
};
